### ISSUE TITLE
Suggestion: Default to MIT license

### ISSUE THREAD

**Issue by wch** [isabelizimm/cookiecutter-custompy#6]
Most of the packages we create will be released under MIT, so it would be good to use that as the default.

Also, the current LICENSE file has someone's name in it -- probably best to make it so that name is filled in automatically:
https://github.com/isabelizimm/cookiecutter-custompy/blob/f712e4b5314dfdc8f031c0263c9236bc61707da4/LICENSE#L1

**Comment by isabelizimm** [comment]
Ah, good catch! That file is for the cookie cutter repo itself, rather than the generated package from cookie cutter use. Let me change the license anyway to avoid confusion. The output of the generated package is visible in the [{{cookiecutter.project_slug}}](https://github.com/isabelizimm/cookiecutter-custompy/tree/main/%7B%7Bcookiecutter.project_slug%7D%7D) directory.

When creating a package, there are 2 options: MIT License or non-open source, with the default being MIT, and it automatically fills in with RStudio copyright, rather than a name. 

https://github.com/isabelizimm/cookiecutter-custompy/blob/f712e4b5314dfdc8f031c0263c9236bc61707da4/%7B%7Bcookiecutter.project_slug%7D%7D/LICENSE#L3

**Comment by wch** [comment]
Ah, that makes sense. Sorry for the confusion!
